-- crawlbtc fresh-install schema.
-- Matches the tables/columns of the legacy db2/schema_all.sql (the data
-- contact points are identical) but without the duplicate indexes and with
-- the 'p2pk' address_type used for Satoshi-era raw-pubkey outputs.
-- Run as a role that may create schemas, e.g.:
--   psql -U pgadmin -d crawlbtc -f schema.sql

CREATE SCHEMA IF NOT EXISTS blockchain;

DO $$ BEGIN
  CREATE TYPE blockchain.address_type AS ENUM
    ('p2pkh', 'p2sh', 'bech32', 'taproot', 'unknown', 'p2pk');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE blockchain.balance_job_status AS ENUM
    ('pending', 'in_progress', 'done', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE blockchain.block_feature AS ENUM
    ('vin', 'vout', 'both', 'none', 'op_return_only', 'coinbase_only');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE blockchain.block_job_status AS ENUM
    ('pending', 'in_progress', 'done', 'skipped', 'failed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE blockchain.tx_io_type AS ENUM ('in', 'out');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE blockchain.tx_type AS ENUM
    ('standard', 'coinbase', 'segwit', 'unknown');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION blockchain.touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

CREATE TABLE IF NOT EXISTS blockchain.block_jobs (
    height integer PRIMARY KEY,
    status blockchain.block_job_status DEFAULT 'pending' NOT NULL,
    updated_at timestamp without time zone DEFAULT now(),
    features blockchain.block_feature DEFAULT 'none' NOT NULL,
    vout_status blockchain.block_job_status DEFAULT 'pending' NOT NULL,
    vin_status blockchain.block_job_status DEFAULT 'pending' NOT NULL,
    address_status blockchain.block_job_status DEFAULT 'pending' NOT NULL
);

CREATE TABLE IF NOT EXISTS blockchain.blocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_hash text NOT NULL UNIQUE,
    height integer NOT NULL UNIQUE,
    "timestamp" timestamp without time zone NOT NULL,
    processed_at timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS blockchain.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txid text NOT NULL UNIQUE,
    block_hash text,
    received_time timestamp without time zone NOT NULL,
    total_in bigint,
    total_out bigint,
    tx_type blockchain.tx_type DEFAULT 'unknown'
);

CREATE TABLE IF NOT EXISTS blockchain.transaction_io (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txid text NOT NULL,
    address text,
    amount bigint,
    io_type blockchain.tx_io_type NOT NULL,
    idx integer NOT NULL,
    address_type blockchain.address_type DEFAULT 'unknown',
    CONSTRAINT transaction_io_unique_txid_type_idx UNIQUE (txid, io_type, idx)
);

CREATE TABLE IF NOT EXISTS blockchain.spends (
    prev_txid text NOT NULL,
    prev_vout integer NOT NULL,
    spending_txid text NOT NULL,
    spending_vin integer NOT NULL,
    spent_height integer,
    spent_block text,
    spent_time timestamp with time zone,
    CONSTRAINT spends_pkey PRIMARY KEY (prev_txid, prev_vout),
    CONSTRAINT spends_spending_txid_spending_vin_key UNIQUE (spending_txid, spending_vin)
);

CREATE TABLE IF NOT EXISTS blockchain.watch_addresses (
    address text PRIMARY KEY,
    address_type blockchain.address_type,
    public_key_hex text,
    private_key_wif text,
    private_key_hex text,
    derivation_path text,
    label text,
    tags jsonb DEFAULT '[]'::jsonb NOT NULL,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    tx_count integer DEFAULT 0 NOT NULL CHECK (tx_count >= 0),
    utxo_count integer DEFAULT 0 NOT NULL CHECK (utxo_count >= 0),
    balance_sats bigint DEFAULT 0 NOT NULL CHECK (balance_sats >= 0),
    last_scanned_height integer,
    last_scanned_time timestamp with time zone,
    last_scanned_txid text,
    balance_status blockchain.balance_job_status DEFAULT 'pending' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT watch_addresses_tags_check CHECK (jsonb_typeof(tags) = 'array')
);

DO $$ BEGIN
  CREATE TRIGGER watch_addresses_touch BEFORE UPDATE ON blockchain.watch_addresses
    FOR EACH ROW EXECUTE FUNCTION blockchain.touch_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Known-entity reference tags (exchanges, mixers, sanctioned/OFAC, ...).
CREATE TABLE IF NOT EXISTS blockchain.entity_tags (
    address      text NOT NULL,
    entity_name  text NOT NULL,
    category     text NOT NULL,
    source       text NOT NULL,
    confidence   real,
    reference    text,
    added_at     timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT entity_tags_pkey PRIMARY KEY (address, source)
);
CREATE INDEX IF NOT EXISTS entity_tags_address_idx  ON blockchain.entity_tags (address);
CREATE INDEX IF NOT EXISTS entity_tags_category_idx ON blockchain.entity_tags (category);
CREATE INDEX IF NOT EXISTS entity_tags_source_idx   ON blockchain.entity_tags (source);

-- Historical BTC price series for fiat valuation (`crawlbtc import-prices`).
CREATE TABLE IF NOT EXISTS blockchain.btc_prices (
    ts        date NOT NULL,
    currency  text NOT NULL,
    price     numeric NOT NULL,
    source    text,
    added_at  timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT btc_prices_pkey PRIMARY KEY (ts, currency)
);
CREATE INDEX IF NOT EXISTS btc_prices_currency_idx ON blockchain.btc_prices (currency, ts);

-- Global wallet clusters (common-input-ownership), built by
-- `crawlbtc build-clusters`. address -> canonical (smallest) cluster address.
CREATE TABLE IF NOT EXISTS blockchain.address_clusters (
    address    text PRIMARY KEY,
    cluster_id text NOT NULL
);
CREATE INDEX IF NOT EXISTS address_clusters_cid_idx
    ON blockchain.address_clusters (cluster_id);

-- Incremental-balance watermark (see `crawlbtc update-balances`): the
-- fully-processed height that a materialized table is exact up to.
CREATE TABLE IF NOT EXISTS blockchain.balance_watermark (
    name       text PRIMARY KEY,
    height     integer NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- Materialized every-address balances, rebuilt by `crawlbtc build-balances`.
CREATE TABLE IF NOT EXISTS blockchain.address_balances (
    address text PRIMARY KEY,
    address_type blockchain.address_type,
    balance_sats bigint NOT NULL,
    utxo_count integer NOT NULL,
    total_received_sats bigint NOT NULL,
    total_spent_sats bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Minimal index set: every remaining index earns its write cost.
CREATE INDEX IF NOT EXISTS block_jobs_vout_sched_idx ON blockchain.block_jobs (height)
    WHERE vout_status = 'pending';
CREATE INDEX IF NOT EXISTS block_jobs_vin_sched_idx ON blockchain.block_jobs (height)
    WHERE vin_status = 'pending'
      AND vout_status IN ('done', 'skipped');
CREATE INDEX IF NOT EXISTS block_jobs_addr_sched_idx ON blockchain.block_jobs (height)
    WHERE address_status = 'pending'
      AND vout_status IN ('done', 'skipped')
      AND vin_status = 'done';

CREATE INDEX IF NOT EXISTS idx_transactions_block_hash ON blockchain.transactions (block_hash);
CREATE INDEX IF NOT EXISTS idx_transactions_received_time ON blockchain.transactions (received_time);

-- (txid, io_type, idx) lookups are covered by the unique constraint.
CREATE INDEX IF NOT EXISTS idx_txio_address_io ON blockchain.transaction_io (address, io_type);

CREATE INDEX IF NOT EXISTS spends_spent_height_idx ON blockchain.spends (spent_height);
CREATE INDEX IF NOT EXISTS spends_spent_time_idx ON blockchain.spends (spent_time);

CREATE INDEX IF NOT EXISTS watch_addresses_addr_type_idx ON blockchain.watch_addresses (address_type);
CREATE INDEX IF NOT EXISTS watch_addresses_last_seen_idx ON blockchain.watch_addresses (last_seen DESC);
CREATE INDEX IF NOT EXISTS watch_addresses_status_idx ON blockchain.watch_addresses (balance_status, last_scanned_height);
CREATE INDEX IF NOT EXISTS watch_addresses_tags_gin ON blockchain.watch_addresses USING gin (tags);
